language: php

dist: trusty
sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - admin/node_modules
    - client/node_modules

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - APP_ENV=prod
    - KUBERNETES_ENV=prod
    - IP="--set ingress.annotations.kubernetes.io/ingress.global-static-ip-name: api-platform-demo-ip"

before_install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash -s -- --version v2.9.1;
  - sudo apt-get install gcc python-dev python-setuptools
  - sudo easy_install -U pip
  - sudo pip uninstall crcmod
  - sudo pip install -U crcmod
  - |
    if [ TRAVIS_BRANCH != "master" ] || [ $TRAVIS_REPO_SLUG != "api-platform/demo" ]; then
      IP=""
      KUBERNETES_ENV=staging;
    fi

before_script:
  - phpenv config-rm xdebug.ini
  - sudo service mysql stop
  - sudo service postgresql stop
  - npm install -g react-scripts
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - docker-compose up -d
  - helm lint api/helm/api/
  - sleep 20
  - docker-compose exec php composer install -o -n
  - docker-compose exec php bin/console security:check
  - docker-compose exec php bin/console doctrine:schema:validate --skip-sync
  - docker-compose exec php bin/console doctrine:schema:drop --force
  - docker-compose exec php bin/console doctrine:schema:create
  - docker-compose exec php bin/console hautelook:fixtures:load -n
  - docker-compose exec php bin/console doctrine:schema:drop --env=test --force
  - docker-compose exec php bin/console cache:warmup --env=test
  - docker-compose exec php bin/behat
  - curl http://localhost
  - curl http://localhost:81
  - curl http://localhost:8080
  - curl http://localhost:8081
  - curl -k https://localhost
  - curl -k https://localhost:444
  - curl -k https://localhost:8443
  - curl -k https://localhost:8444

# TODO: Keep looking to https://github.com/kubernetes/kubernetes/pull/64034 tests in order to use "wait" with new implementation (in order to replace sleep 60).
# For now we let bucket management available in both prod and staging untill ready
after_success:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - echo -n ${TRAVIS_SERVICE_ACCOUNT_KEY} | base64 -d > travis-service-account.json
  - gcloud auth activate-service-account ${TRAVIS_SERVICE_ACCOUNT} --key-file travis-service-account.json --project=${PROJECT_NAME}
  - gcloud config set compute/zone europe-west1-c
  - gcloud config set project ${PROJECT_NAME}
  - gcloud container clusters get-credentials api-platform-demo --zone europe-west1-c --project ${PROJECT_NAME}
  - helm init --upgrade
  - kubectl delete namespace $(kubectl get namespaces -l app=api-demo-${KUBERNETES_ENV} -o jsonpath="{.items[0].metadata.name}" --ignore-not-found) --ignore-not-found
  - helm dependencies update ./api/helm/api
  - docker build --pull -t eu.gcr.io/${PROJECT_NAME}/php-${KUBERNETES_ENV} -t eu.gcr.io/${PROJECT_NAME}/php-${KUBERNETES_ENV}:latest api --target api_platform_php
  - docker build --pull -t eu.gcr.io/${PROJECT_NAME}/nginx-${KUBERNETES_ENV} -t eu.gcr.io/${PROJECT_NAME}/nginx-${KUBERNETES_ENV}:latest api --target api_platform_nginx
  - docker build --pull -t eu.gcr.io/${PROJECT_NAME}/varnish-${KUBERNETES_ENV} -t eu.gcr.io/${PROJECT_NAME}/varnish-${KUBERNETES_ENV}:latest api --target api_platform_varnish
  - gcloud docker -- push eu.gcr.io/${PROJECT_NAME}/php-${KUBERNETES_ENV}:latest
  - gcloud docker -- push eu.gcr.io/${PROJECT_NAME}/nginx-${KUBERNETES_ENV}:latest
  - gcloud docker -- push eu.gcr.io/${PROJECT_NAME}/varnish-${KUBERNETES_ENV}:latest
  - helm install --wait --namespace=${TRAVIS_COMMIT} ./api/helm/api --set php.repository=eu.gcr.io/${PROJECT_NAME}/php-${KUBERNETES_ENV} --set nginx.repository=eu.gcr.io/${PROJECT_NAME}/nginx-${KUBERNETES_ENV} --set varnish.repository=eu.gcr.io/${PROJECT_NAME}/varnish-${KUBERNETES_ENV} --set secret=${APP_SECRET} --set postgresUser=${DATABASE_USER},postgresPassword="${DATABASE_PASSWORD}",postgresDatabase=${DATABASE_NAME} --set postgresql.persistence.enabled=true ${IP}
  - sleep 60
  - kubectl exec -it $(kubectl --namespace=${TRAVIS_COMMIT} get pods -l app=api-php -o jsonpath="{.items[0].metadata.name}") --namespace=${TRAVIS_COMMIT} -- ash -c 'export APP_ENV=dev && composer install -n && bin/console d:s:u --force --env=dev && bin/console hautelook:fixtures:load -n && APP_ENV=prod composer --no-dev install --classmap-authoritative && bin/console d:s:u --env=prod'
  - kubectl label namespace ${TRAVIS_COMMIT} app=api-demo-${KUBERNETES_ENV}
  - export REACT_APP_API_ENTRYPOINT_IP=$(kubectl --namespace `echo ${TRAVIS_COMMIT}` get ingress -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}')
  - cd admin && yarn && REACT_APP_API_ENTRYPOINT=http://${REACT_APP_API_ENTRYPOINT_IP} yarn build --environment=prod && gsutil -m -o rsync -R build gs://demo-admin.les-tilleuls.solutions
  - cd ../client && yarn && REACT_APP_ADMIN_HOST_HTTP=http://demo-admin.les-tilleuls.solutions REACT_APP_API_HOST_HTTP=http://${REACT_APP_API_ENTRYPOINT_IP}:80 REACT_APP_API_HOST_HTTPS=https://${REACT_APP_API_ENTRYPOINT_IP}:443 yarn build --environment=prod && gsutil -m -o rsync -R build gs://demo-client.les-tilleuls.solutions
  - gcloud auth revoke ${TRAVIS_SERVICE_ACCOUNT}
